# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build React App

  jobs:
  - job: Buildjob
    displayName: Install build and publish
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '22.x'

      - script: npm install
        displayName: Installing project dependencies

      - script: npm run build
        displayName: build the react app step

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: 'build'
          ArtifactName: 'react-build'
          publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy to Azure App Service

  dependsOn: Build

  jobs:

  - deployment: DeployWeb
    displayName: Deploy React App

    environment: production

    strategy:
      runOnce:
        deploy:

          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'react-build'
              downloadPath: '$(Pipeline.Workspace)'

          

          - task: AzureRmWebAppDeployment@5
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'azure-service-connection'
              appType: 'webAppLinux'
              WebAppName: 'khushi-react-portfolio'
              packageForLinux: '$(Pipeline.Workspace)/react-build'
              RuntimeStack: 'NODE|22-lts'
              DeploymentTypeLinux: 'oneDeploy'